4.1 WarmingUpExercise: Basic Vector and Matrix Operation with Numpy

 Problem- 1: Array Creation

In [1]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty array 2x2:\n", empty_array)

ones_array = np.ones((4, 2))
print("\nAll ones array 4x2:\n", ones_array)

filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nArray filled with 7:\n", filled_array)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros array like given array:\n", zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\nOnes array like given array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nNumpy array from list:\n", array_from_list)


Empty array 2x2:
 [[2.43869970e-315 0.00000000e+000]
 [4.24370663e-307 0.00000000e+000]]

All ones array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array like given array:
 [[0 0]
 [0 0]]

Ones array like given array:
 [[1 1]
 [1 1]]

Numpy array from list:
 [1 2 3 4]


 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

In [2]:
import numpy as np

arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr1)

arr2 = np.arange(9).reshape((3, 3))
print("\n2. 3x3 matrix 0 to 8:\n", arr2)

identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

random_arr = np.random.random(30)
mean_value = random_arr.mean()
print("\n4. Random array of size 30:\n", random_arr)
print("Mean of the array:", mean_value)

random_matrix = np.random.random((10, 10))
min_val = random_matrix.min()
max_val = random_matrix.max()
print("\n5. 10x10 random matrix:\n", random_matrix)
print("Min value:", min_val, "Max value:", max_val)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

n, m = 5, 5
border_array = np.ones((n, m))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)


1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.9758706  0.49629428 0.95626441 0.2450988  0.02411143 0.4010456
 0.52026249 0.69891221 0.59976003 0.20003749 0.22641436 0.53558194
 0.68103041 0.85894329 0.43022148 0.35322329 0.28602145 0.04653029
 0.13962216 0.65486736 0.97314169 0.81568877 0.89753024 0.64440711
 0.7907597  0.39376649 0.22434725 0.99229932 0.29446558 0.72924491]
Mean of the array: 0.536192147993276

5. 10x10 random matrix:
 [[0.65181515 0.33504934 0.92180105 0.73032645 0.3368647  0.6762208
  0.45517528 0.76716482 0.25454906 0.95719698]
 [0.20701189 0.41626945 0.76151004 0.10185934 0.42568045 0.21035296
  0.15577723 0.45234465 0.25020975 0.12730034]
 [0.88565137 0.69536875 0.27249464 0.87448451 0.13446677 0.04591534
  0.91039006

Problem- 3: Array Operations:

In [3]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("1. x + y:\n", add_xy)

sub_xy = x - y
print("\n2. x - y:\n", sub_xy)

mul_x = x * 3
print("\n3. x * 3:\n", mul_x)

square_x = x ** 2
print("\n4. Square of x:\n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("v . w =", dot_vw)
print("x .v =", dot_xv)
print("x . y =\n", dot_xy)

concat_row_xy = np.concatenate((x, y), axis=0)
concat_col_vw = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\n6. Concatenations:")
print("x and y along row:\n", concat_row_xy)
print("v and w along column:\n", concat_col_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print("\n7. Concatenate x and v error:\n", concat_xv_error)


1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. Square of x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v . w = 219
x .v = [29 77]
x . y =
 [[19 22]
 [50 58]]

6. Concatenations:
x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column:
 [[ 9 11]
 [10 12]]

7. Concatenate x and v error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:

In [6]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

 1. Prove A.A−1 = I.

In [7]:
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A_inv =\n", identity)

A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB̸ = BA.

In [9]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal? False


3. Prove (AB)T = BTAT

In [8]:
AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)

print("\n(AB)^T =\n", AB_T)
print("B^T A^T =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))


(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Are they equal? True


 Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

Step 1: Represent in matrix form AX = B

In [10]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A_inv =\n", identity)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)
print("\n3. (AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

B_sys = np.array([-1, -3, 9])


1. A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal? False

3. (AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Are they equal? True
